apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services
  template:
    metadata:
      labels:
        app: services
    spec:
      containers:
        - name: services
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: services-service
spec:
  selector:
    app: services
  type: NodePort
  ports:
  - protocol: TCP
        port: 80
        targetPort: 8080
        nodePort: 30080
